spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/order/**
          filters:
            - TokenFilter
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product/**
          filters:
            - TokenFilter
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/inventory/**
          filters:
            - TokenFilter
      default-filters:
        - name: Fallback
          args:
            fallbackUri: forward:/fallback

---

server:
  port: 8080
