spring:
  application:
    name: USER-SERVICE # Name of your microservice, visible in Eureka dashboard

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server
    register-with-eureka: true                   # Register this service with Eureka
    fetch-registry: true                         # Fetch the registry of other services

  instance:
    prefer-ip-address: true                      # Use IP address instead of hostname for service registration
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port} # Unique identifier for this instance

